services:
  web-portofolio:
    image: node:lts
    user: node
    container_name: web-portofolio
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
      - "5173:5173"
      - "4173:4173"
    environment:
      NODE_ENV: development
    stdin_open: true
    tty: true
    command: bash -c "tail -f /dev/null"
